apiVersion: v1
kind: Pod
metadata:
  name: c4ui
spec:
  restartPolicy: Never

  volumes:
    - name: structurizr-data
      emptyDir: {}

  containers:
    - name: structurizr
      image: structurizr/lite
      volumeMounts:
        - name: structurizr-data
          mountPath: /usr/local/structurizr

    - name: handler
      image: handler
      imagePullPolicy: Never
      volumeMounts:
        - name: structurizr-data
          mountPath: /usr/local/structurizr
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: github-token
              optional: false
